### ISSUE TITLE
Feat: create styleguide rule for providers

### ISSUE THREAD

**Issue by tuxmachine** [TrilonIO/eslint-plugin#13] opened 2023-12-20 13:22 UTC
# Description

Large teams can have the desire to limit or enforce a particular style of creating providers; e.g. banning request-scoped providers.

# Acceptance Criteria

tbd needs more refinement

**Comment by tuxmachine** [comment] 2024-01-23 13:38
Perhaps we can take https://github.com/nestjs/nest/pull/12753 into account

**Comment by thiagomini** [comment] 2024-02-28 12:20
Duplicate of #24

**Closed by thiagomini** 2024-02-28 12:20 UTC
Labels: enhancement
